### ISSUE TITLE
Question: Change endpoint (base URI?) for LUIS

### ISSUE THREAD

**Issue by bjaanes** [Azure-Samples/Cognitive-Speech-STT-Android#36]
Like the title says, is it possible to change the endpoint to not use west USA?

The question is also asked here:
http://stackoverflow.com/questions/44048081/how-to-change-endpoint-for-android-speech-langauge-understanding-luis-sdk

I will update both locations as soon as I have an answer.

**Comment by priyaravi20** [comment]
Its not available as a configuration that can be changed. What endpoint are you trying to use?

**Comment by bjaanes** [comment]
Oh, it should be. I want to use west eu.

**Comment by priyaravi20** [comment]
One workaround I can suggest is to use STT without intent and call LUIS API directly to get the intent until we  provide this functionality.

**Comment by bjaanes** [comment]
That is a potential workaround, but not one I like :) I hope you will provide that functionality in the SDK.

**Comment by paolo2331** [comment]
To use european LUIS endpoint within Bot Builder C# SDK, just modify Luis Model parameters as follows:

[LuisModel("YOUR-LUIS-APP-ID", "YOUR-LUIS-EUROPEAN-KEY", domain: "westeurope.api.cognitive.microsoft.com")]
Note that you'll need to export your LUIS app over EU.LUIS in order to access the correct endpoint.

Hope it helps.
